version: '3'
services:
  battproxy:
    image: 'nginx:alpine'
    ports:
      - '80:80'
      # - '8081:8081'
    restart: always
    networks:
      - main
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/:/usr/share/nginx/html/'
  portainer:
    image: 'portainer/portainer-ce:latest'
    command: '-H unix:///var/run/docker.sock'
    restart: always
    networks:
      - main
    ports:
      - '8000:8000'
      - '9000:9000'
      - '9443:9443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
networks:
    main: null
volumes:
    portainer_data: null
    firefly_iii_upload: null
    firefly_iii_db: null